services:
  mongo:
    image: mongo:7
    container_name: fxdc-camp-mongo
    ports:
      - "27017:27017"
    volumes:
      - fxdc_mongo_data:/data/db
    restart: unless-stopped

volumes:
  fxdc_mongo_data:
